# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [5]:
import numpy as np 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))
'''
empty不像zeros一樣，一開始就將每個元素設為0
但優點是可以快速製造出一矩陣
'''

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


'\nempty不像zeros一樣，一開始就將每個元素設為0\n但優點是可以快速製造出一矩陣\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [13]:
# 參考解答

a = np.random.rand(2, 3)

print(a)


print(np.array(a, dtype='int8'))
print(np.floor(a))

[[0.93087556 0.78702174 0.25329332]
 [0.94607392 0.18392044 0.66527923]]
[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [16]:
m = 20
n = 40
'''
method 1
'''
from numpy.random import default_rng

print(default_rng().integers(m, n, size=(2,3)))

[[23 22 25]
 [24 26 21]]


In [18]:
'''
method 2
'''
print(np.random.randint(0, 10, size=(2,3)))

[[1 0 6]
 [5 1 1]]
