# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [13]:
# 記得先 Import 正確的套件

import numpy as np

In [14]:
a=np.arange(1,12)
b=[]
for i in a:
    if i>=3 and i<=6:
       i=i*(-1) 
       b.append(i)
    else:
        b.append(i)
b

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [15]:
A = np.random.rand(3, 6)
print(A)
print(A[A>0.5])

[[0.19481471 0.93338664 0.0307896  0.73024126 0.77122597 0.26403862]
 [0.74977011 0.10160824 0.86341976 0.52761677 0.71999865 0.47605679]
 [0.27174796 0.36612532 0.68116718 0.78966647 0.94027251 0.52459492]]
[0.93338664 0.73024126 0.77122597 0.74977011 0.86341976 0.52761677
 0.71999865 0.68116718 0.78966647 0.94027251 0.52459492]
