# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np

a = np.arange(6).reshape(2,3)
print(a.sum())
print(np.sum(a))
print(sum(a))
'''
a.sum() 對多維的陣列進行操作，可以設定 Axis 的參數
np.sum(a) 在多維度下，亦可設定 Axis 參數
sum(a) 在多維度下，則是回傳 Axis=0的值
不過在一維度下，無差別
'''

15
15
[3 5 7]


'\na.sum() 對多維的陣列進行操作，可以設定 Axis 的參數\nnp.sum(a) 在多維度下，亦可設定 Axis 參數\nsum(a) 在多維度下，則是回傳 Axis=0的值\n不過在一維度下，無差別\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [6]:
# 記得先 Import 正確的套件

import numpy as np
'''
正規化是將資料等比例縮放到 [0, 1] 區間中
'''

'\n正規化是將資料等比例縮放到 [0, 1] 區間中\n'

In [7]:
A = np.random.random((5, 5))
print(A)
normalA = (A-A.min())/(A.max()-A.min())
print(normalA)

[[0.89385689 0.19030355 0.58034032 0.4784624  0.34048495]
 [0.08388419 0.76633631 0.20470086 0.58068533 0.04092804]
 [0.01178321 0.74828985 0.94736209 0.40145545 0.37928856]
 [0.31017756 0.87760397 0.71311086 0.03696668 0.96776042]
 [0.53282555 0.40718429 0.45256669 0.32518187 0.81378942]]
[[0.92269321 0.18674121 0.59473919 0.48816979 0.34383847]
 [0.07542124 0.7893003  0.20180152 0.59510009 0.03048695]
 [0.         0.7704228  0.97866232 0.40761667 0.38442899]
 [0.31213543 0.90569185 0.73362382 0.02634317 1.        ]
 [0.54503636 0.41360932 0.46108158 0.32783068 0.83893863]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [11]:
import numpy as np

a = np.random.random((10))
print(a)

a[a.argmax()]=-1

print(a)

[0.6265457  0.40227508 0.66497841 0.82754103 0.12004637 0.3783523
 0.01505355 0.96342438 0.89761401 0.09501536]
[ 0.6265457   0.40227508  0.66497841  0.82754103  0.12004637  0.3783523
  0.01505355 -1.          0.89761401  0.09501536]
